- hosts: prod-server
  become: true
  tasks:
  - name: update cache
    apt:
      update_cache: yes

  - name: install docker
    apt:
      pkg: docker.io
      state: present

  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true

  - name: List all running Docker containers
    command: docker ps -q
    register: running_container_ids
    changed_when: false

  - name: Stop all running Docker containers
    command: docker stop {{ item }}
    loop: "{{ running_container_ids.stdout_lines }}"


  - name: deploy to prod-server
    command: docker run -itd -p 8082:8082 manofoever/medicure:1.0
